defaults: &defaults
  twilio:
    sid:    <%= ENV["twilio_sid"] %>
    token:  <%= ENV["twilio_token"] %>
    number: <%= ENV["twilio_number"] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
